name = "schema-ehnemark"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "schema-ehnemark-db"
database_id = "a9e299af-3cf4-4009-bfea-860fcb6542d2"
